name: catch-test 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-all:
    name: Linux 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        cmake ./
        gcc --version
        make
    
    - name: Run tests
      run: ./test/rctl_tests
